ActividadJSF/src/java/Controladores/EstudianteManagedBean.java
package Controladores;

import Entidades.Estudiante;
import Modelos.EstudianteModel;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import java.io.Serializable;
import java.util.List;


@Named(value = "BEstudiante")
@SessionScoped
public class EstudianteManagedBean implements Serializable {

    private Estudiante estu = new Estudiante();
    private EstudianteModel esmodel = new EstudianteModel();
    
    public EstudianteManagedBean() {
    
    }

    public Estudiante getEstu() {
        return estu;
    }

    public void setEstu(Estudiante estu) {
        this.estu = estu;
    }

  
   
    public String Agregar() {
        esmodel.registrar(this.estu);
        this.estu = new Estudiante();
        
        return "index?faces-redirect=true";
    }

    public String Editar() {
        esmodel.editar(this.estu);
        this.estu = new Estudiante();
        
        return "index?faces-redirect=true";
    }

    public String Eliminar() {
        esmodel.eliminar(this.estu);
        this.estu = new Estudiante();
        
        return "index?faces-redirect=true";
    }
    
    public List<Estudiante> getListaEstudiante() {
        return esmodel.listaa();
    }
}

ActividadJSF/web/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
      <title>Facelet Title</title>
        <link href="recursos/css/estilos.css" rel="stylesheet" type="text/css"/>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous"/>
    </h:head>
    <h:body>
        <div class="container"> 
        <h:form>
            <br/>
             <label>ID: </label>
             <h:inputText value="#{BEstudiante.estu.id}"  /> <br/>
                 <label>Nombre: </label>
            <h:inputText value="#{BEstudiante.estu.nombre}" /> <br/>
                <label>Edad: </label>
                <h:inputText value="#{BEstudiante.estu.edad}" /> <br/>
                <br/>
            <div class="btn-group" role="group" aria-label="Basic example" >
            <h:commandButton action="#{BEstudiante.Agregar()}" value="Agregar Estudiante" class="btn btn-primary"/>
            <h:commandButton action="#{BEstudiante.Editar()}" value="Editar Estudiante" class="btn btn-warning"/>
              <h:commandButton class="btn btn-danger" value="Eliminar Estudiante" action="#{BEstudiante.Eliminar()}"/>
              </div>
  </h:form>

        <h1> Personas Registradas  </h1>
        <h:form>
        <h:dataTable value="#{BEstudiante.listaEstudiante}" var="p" class="table table-dark"> 
            <h:column> 
                <f:facet name="header"> ID </f:facet>
                #{p.id}
        </h:column> 
            <h:column>
                <f:facet name="header"> Nombre </f:facet>
                #{p.nombre}
            </h:column>
             <h:column>
                <f:facet name="header"> Edad </f:facet>
                #{p.edad}
            </h:column>
                         
        </h:dataTable>
        </h:form>
        
        
       </div>
    
    </h:body>
</html>